# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
        # Test with a matrix of Node.js versions
        node-version: [24]
        # Optional: you can add other versions like 20, 22
        # node-version: [20, 22, 24]
        # See supported Node.js versions in the setup-node documentation
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26.1'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
